version: '3'

services:
  common: &BASE
    environment:
      - PORT=4000
      - CORS_WHITELIST=http://localhost:3333
      - DATABASE_URL=postgresql://postgres:dummy_password@db:5432/localdb?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_QUERY_FIND_MANY_MAX_TIME=3600
    build:
      context: .
      dockerfile: Dockerfile

  redis:
    image: redis:7-alpine
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - /var/lib/redis/data:/var/lib/redis/data
    networks:
      - docker-net

  db:
    image: postgres:12.10
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - docker-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dummy_password
      POSTGRES_DB: localdb

  db-migrate:
    <<: *BASE
    command: yarn migrate:deploy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/services/prisma/prisma/client
    networks:
      - docker-net
    depends_on:
      - db

  web-service:
    <<: *BASE
    command: yarn start:service:web
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/services/prisma/prisma/client
    networks:
      - docker-net
    depends_on:
      - db
      - redis
    ports:
      - 4000:4000

networks:
  docker-net:
    name: docker-net
