version: '3'

# Global variables
x-global-vars: &global-vars
  CORS_WHITELIST: http://localhost:3333
  DATABASE_URL: postgresql://postgres:dummy_password@db:5432/localdb?schema=public
  RATE_TTL: 60
  RATE_LIMIT: 60

services:
  common: &BASE
    build:
      context: .
      dockerfile: Dockerfile

  redis:
    image: redis:7-alpine
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - /var/lib/redis/data:/var/lib/redis/data
    networks:
      - docker-net

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis:redis:6379
    depends_on:
      - redis
    networks:
      - docker-net
    ports:
      - 8081:8081

  storage:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=dumm_minio_user
      - MINIO_ROOT_PASSWORD=dummy_minio_password
    volumes:
      - /var/lib/minio/data:/data
    networks:
      - docker-net
    command: server --console-address :9001 ./data

  db:
    image: postgres:12.10
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - docker-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dummy_password
      POSTGRES_DB: localdb

  db-migrate:
    <<: *BASE
    command: yarn migrate:deploy
    environment:
      <<: *global-vars
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/services/prisma/prisma/client
    networks:
      - docker-net
    depends_on:
      - db

  app-service:
    <<: *BASE
    command: yarn start:service:app
    environment:
      <<: *global-vars
      PORT: 4001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/services/prisma/prisma/client
    networks:
      - docker-net
    depends_on:
      - db
    ports:
      - 4001:4001

  feature-service:
    <<: *BASE
    command: yarn start:service:feature
    environment:
      <<: *global-vars
      PORT: 4002
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/services/prisma/prisma/client
    networks:
      - docker-net
    depends_on:
      - db
    ports:
      - 4002:4002

  storage-service:
    <<: *BASE
    command: yarn start:service:storage
    environment:
      <<: *global-vars
      PORT: 4003
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/services/prisma/prisma/client
    networks:
      - docker-net
    depends_on:
      - db
      - storage
    ports:
      - 4003:4003

  nginx:
    image: nginx:latest
    ports:
      - 4000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-service
      - feature-service
      - storage-service
    networks:
      - docker-net

networks:
  docker-net:
    name: docker-net
